#:kivy 1.0.9

ScreenManager:
    MysteryPageA: 
        name:"MysteryPageA"
    MysteryPageB: 
        name:"MysteryPageB"

<MysteryPageA>:
    MDLabel:
        text: 'MysteryPageA'
        font_style: 'H3'
        pos_hint: {'center_x': 0.5, 'center_y': 0.8}
        halign: 'center'
    MyButton:
        text: 'Next'
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        on_release: root.try_change()

<MysteryPageB>:
    MDLabel:
        text: 'MysteryPageB'
        font_style: 'H3'
        pos_hint: {'center_x': 0.5, 'center_y': 0.8}
        halign: 'center'
    MyButton:
        text: 'Back'
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        on_release: root.try_change()

<MyButton@Button>
    background_color: 'blue'
    style: 'CustomButton'
    size_hint: 0.2, 0.1
